### ISSUE TITLE
Followed README.md instructions, cannot install

### ISSUE THREAD

**Issue by bcornw2** [DiscreteTom/if-maker#11]
Hello, 

I downloaded ifm to my root folder, as specified in the readme, and everytime i try to run: python ifm.py install, I get the following error.

```
$ python ifm.py install 
  File "ifm.py", line 12
    def processCode(code: str) -> str:
                        ^
SyntaxError: invalid syntax
```

Am I doing something wrong?

**Comment by DiscreteTom** [comment]
Hi, @bcornw2 
Just try `python3 ifm.py install` because python 2.x does not support type hint yet. 🙂
